### PR TITLE
Update StoryMain.txt

### PR DESCRIPTION
**Pull request by FinnRayXuvgo**

### CODE REVIEW

**Comment by U23RN6M3** [comment]
i'm gonna comment on this pull request cause I'm waiting for jeaikr to accept it

**Comment by FinnRayXuvgo** [comment]
no way, me too @U23RN6M3

**Comment by U23RN6M3** [comment]
yo bro how did u come up with this pristine plot you suggested? @FinnRayXuvgo

**Comment by FinnRayXuvgo** [comment]
idk bro I just make up this stuff naturally

**Comment by U23RN6M3** [comment]
I wonder when jeaikr will see this

**Comment by FinnRayXuvgo** [comment]
same

**Comment by jeaikr** [comment]
🙆🏻‍♀️

**Pull request merged**
